import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";
import { FaHome, FaSignInAlt, FaUserPlus } from "react-icons/fa"; 
import { AuthProvider } from "./lib/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Frontend Laboratory App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
        <AuthProvider>
          
          <aside className="w-1/4 bg-gradient-to-b from-gray-800 to-gray-900 text-white h-screen flex flex-col items-center p-6">
            <h1 className="text-2xl font-bold mt-6 mb-4">Menu</h1>
            <nav className="flex flex-col w-full space-y-4">
              <Link
                href="/"
                className="flex items-center px-6 py-3 hover:bg-gray-700 rounded-xl w-full transition-colors"
              >
                <FaHome className="mr-3 text-xl" /> Home
              </Link>
              <Link
                href="/user/signin"
                className="flex items-center px-6 py-3 hover:bg-gray-700 rounded-xl w-full transition-colors"
              >
                <FaSignInAlt className="mr-3 text-xl" /> Sign In
              </Link>
              <Link
                href="/user/register"
                className="flex items-center px-6 py-3 hover:bg-gray-700 rounded-xl w-full transition-colors"
              >
                <FaUserPlus className="mr-3 text-xl" /> Register
              </Link>
              <Link
                href="/user/simon_says"
                className="flex items-center px-6 py-3 hover:bg-gray-700 rounded-xl w-full transition-colors"
              >
                <FaUserPlus className="mr-3 text-xl" /> Simon Says
              </Link>
            </nav>
          </aside>

          
          <main className="flex-1 flex flex-col bg-gray-50">
            
            <header className="bg-gradient-to-r from-gray-50 to-gray-100 p-6 shadow-lg flex justify-between items-center rounded-b-xl">
              <h1 className="text-2xl font-bold text-gray-800">Frontend Laboratory App</h1>
              <div className="space-x-6">
                <Link
                  href="/user/signin"
                  className="text-blue-600 hover:underline font-semibold transition-colors"
                >
                  Log In
                </Link>
                <Link
                  href="/user/register"
                  className="text-blue-600 hover:underline font-semibold transition-colors"
                >
                  Register
                </Link>
              </div>
            </header>

            
            <section className="flex-1 p-6">{children}</section>

           
            <footer className="bg-gradient-to-r from-gray-800 to-gray-900 text-white p-6 text-center text-sm rounded-t-xl">
              &copy; 2024 Frontend Laboratory. All rights reserved.
            </footer>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
